### ISSUE TITLE
there's no css

### ISSUE THREAD

**Issue by janat08** [JSEcoin/website#4]

**Comment by JohnRSim** [comment]
Please can you provide more info?
If you are using an adblocker - that may be causing the issue?

The site appears fine when I load it -
![image](https://user-images.githubusercontent.com/364208/59744437-7fcf6e00-926a-11e9-9b2e-83a724b958c1.png)

**Comment by janat08** [comment]
Happened in ublock origin extension, but I suppose you don't have a working relationship to appeal their selectors for blocking.

**Comment by JohnRSim** [comment]
https://github.com/uBlock-LLC/uBlock/issues/1774
We have followed up a few times with uBlock - as you can see from this post however have been unsuccessful with getting them to fix the issue.
